name: Invoke AWS Lambda with User Inputs

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for the new user'
        required: true
      email:
        description: 'Email address of the new user'
        required: true
      tag:
        description: 'Tag associated with the new user'
        required: true

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install boto3
        run: pip install boto3

      - name: Invoke AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Replace with your AWS region
        run: |
          import boto3
          import json

          # Initialize the Lambda client
          lambda_client = boto3.client('lambda', region_name='us-east-1')

          # Prepare the payload
          payload = {
              'username': '${{ github.event.inputs.username }}',
              'email': '${{ github.event.inputs.email }}',
              'tag': '${{ github.event.inputs.tag }}'
          }

          # Invoke the Lambda function
          response = lambda_client.invoke(
              FunctionName='create_user',
              InvocationType='RequestResponse',
              Payload=json.dumps(payload)
          )

          # Read and print the response
          response_payload = json.loads(response['Payload'].read())
          print(response_payload)
